export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const SIGNIN_START = 'SIGNIN_START';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';
export const SIGNOUT = 'SIGNOUT';

export const FETCH_ACCOUNTS_START = 'FETCH_ACCOUNTS_START';
export const FETCH_ACCOUNTS_SUCCESS = 'FETCH_ACCOUNTS_SUCCESS';
export const FETCH_ACCOUNTS_FAIL = 'FETCH_ACCOUNTS_FAIL';

export const GET_COUNT_ACCOUNT_START = 'GET_COUNT_ACCOUNT_START';
export const GET_COUNT_ACCOUNT_SUCCESS = 'GET_COUNT_ACCOUNT_SUCCESS';
export const GET_COUNT_ACCOUNT_FAIL = 'GET_COUNT_ACCOUNT_FAIL';